batch_size: [10000]
max_node_size: 20000000
cost_weight: [0.9, 0.6, 0.3]
pop_ratio: [.inf, 0.35, 0.2]
num_eval: 200
run_name: null
scatter_max_points: 200
max_expansion_plots: 3
use_early_stopping: true
early_stop_patience: 10
early_stop_threshold: 0.5
